import mongoose from "mongoose";

const conversationSchema = new mongoose.Schema({
  customer: { type: mongoose.Schema.Types.ObjectId, ref: "Customer" },
  product: { type: mongoose.Schema.Types.ObjectId, ref: "Product" },
  questions: [{ type: mongoose.Schema.Types.ObjectId, ref: "Question" }],
  responses: [{ type: mongoose.Schema.Types.ObjectId, ref: "Response" }],
  summary: String, // generated by Gemini
  dashboardMetrics: {
    satisfactionScore: Number,
    avgResponseTime: Number,
    completionRate: Number
  },
  engagement: {   // Gamified engagement
    rewardPoints: { type: Number, default: 0 },
    personalizedMessages: [String]
  },
},{ timestamps: true });

export const Conversation = mongoose.model("Conversation", conversationSchema);